### ISSUE TITLE
uri is not a function - importing issues

### ISSUE THREAD

**Issue by CherryDT** [mkrause/uri-tag#10]
Hi, trying to use `uri-tag`. I have a problem importing it on the backend in node.js (with Rollup on the frontend it works). I'm on node.js v16.

```javascript
import uri from 'uri-tag'

console.log(uri`https://example.com/${'hello&world'}`)
```

```none
file:///mnt/c/Users/david/proj/test/test.js:3
console.log(uri`https://example.com/${'hello&world'}`)
               ^

TypeError: uri is not a function
    at file:///mnt/c/Users/david/proj/test/src/test:3:16
    at ModuleJob.run (node:internal/modules/esm/module_job:183:25)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)
    at async handleMainPromise (node:internal/modules/run_main:63:12)
```

If I do `console.log(uri)`, I get this:

```none
{
  default: [Function (anonymous)] { raw: [Function: raw] },
  raw: [Function: raw],
  rawSymbol: Symbol(uri.raw)
}
```

This is weird, it's what I'd expect after `import * as uri from 'uri-tag'` but not `import uri from 'uri-tag'` which should return the default export. Note that `import { default as uri } from 'uri-tag'` doesn't work either.

It works when I use `uri.default` instead of `uri`, but that's not how it should be!

**My workaround:** I created another module that imports `uri-tag` and properly reexports it:

```javascript
import uriTagExport from 'uri-tag'
export default uriTagExport.default
export const raw = uriTagExport.raw
export const rawSymbol = uriTagExport.rawSymbol
```

**Comment by mkrause** [comment]
This package doesn't support ES modules at the moment, there's no `exports` configured. PR welcome, or otherwise it'll need to wait until I get around to making this ESM compatible.

**Comment by mkrause** [comment]
As of v2.0, the package has been rewritten with ES modules support so this should be resolved now. Running it through the following tool to check various scenarios shows no known issues at the moment:

https://arethetypeswrong.github.io/?p=uri-tag%402.0.0

Will close this ticket. Please let me know if there are any remaining issues with ESM imports.
